#!/usr/bin/env bash
#
# web-fetch skill init script
# Guides installation of required Python dependencies and records the Python path.
#
# Usage:
#   ./scripts/init.sh [python_path]
#
# Examples:
#   ./scripts/init.sh
#   ./scripts/init.sh /srv/venv/bin/python3

set -euo pipefail

SKILL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CONFIG_FILE="${SKILL_DIR}/.web-fetch.env"

# 1. Pick Python interpreter
if [[ $# -ge 1 ]]; then
    PYTHON="$1"
elif [[ -x /srv/venv/bin/python3 ]]; then
    PYTHON="/srv/venv/bin/python3"
else
    PYTHON="$(command -v python3 || true)"
fi

if [[ -z "${PYTHON}" ]] || [[ ! -x "${PYTHON}" ]]; then
    echo "Error: no usable Python interpreter found." >&2
    echo "Please install Python 3.10+ or pass a path: ./scripts/init.sh /path/to/python3" >&2
    exit 1
fi

echo "Using Python: ${PYTHON}"
"${PYTHON}" --version

# 2. Check required packages
REQUIRED=("scrapling" "html2text" "cloakbrowser")
MISSING=()

for pkg in "${REQUIRED[@]}"; do
    if ! "${PYTHON}" -c "import ${pkg}" 2>/dev/null; then
        MISSING+=("${pkg}")
    fi
done

if [[ ${#MISSING[@]} -gt 0 ]]; then
    echo "Missing packages: ${MISSING[*]}"
    echo "Installing with: ${PYTHON} -m pip install ${MISSING[*]}"
    "${PYTHON}" -m pip install "${MISSING[@]}"
else
    echo "All required packages are already installed."
fi

# 3. Write config with Python path
cat > "${CONFIG_FILE}" <<EOF
# Auto-generated by web-fetch/scripts/init.sh
WEB_FETCH_PYTHON=${PYTHON}
EOF

echo "Config written to: ${CONFIG_FILE}"
echo "You can now run:"
echo "  ${PYTHON} ${SKILL_DIR}/scripts/fetch.py <url>"
